secrets:
- kmsKeyName: projects/graphql-wfs/locations/global/keyRings/graphQL/cryptoKeys/live
  secretEnv:
    OS_KEY: CiQAtMyr9z9pKerbOaHkkXsqSiBm4olI6INVJPcMHS0x7sneqNoSSQBqW3q9GraiXsimyI1f9KH7y8NOYP22+lN7VeUcXJFwn20pJqvAt1ielVVarVjtrEIsh2CM/y0QEn7jSxaPryciEJX4KEiLQm8=

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Create vars.yaml with secret vars
  entrypoint: /bin/sh
  secretEnv: ['OS_KEY']
  args: ['-c', 'echo "OS_KEY: $$OS_KEY" > vars.yaml']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'graphqlwfs', '--runtime', 'python37', '--trigger-http', '--env-vars-file', 'vars.yaml']
