secrets:
- kmsKeyName: projects/graphql-wfs/locations/global/keyRings/graphQL/cryptoKeys/live
  secretEnv:
    OS_KEY: CiQAtMyr98Tf5x+g+EDmhI+5BatnfBd+N0gdEH8hUeNDsJOrFV4SSQBqW3q98p2ErGNiabk1MbrBTWkgwkhCudYVfSnVPvSwxH45Kyqzx28hGnTdsImqClW29QNaxIvX1nECUbGxFdWccJ81UGhEQwg=

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Create vars.yaml with secret vars
  entrypoint: /bin/sh
  secretEnv: ['OS_KEY']
  args: ['-c', 'echo "OS_KEY: $$OS_KEY" > vars.yaml']

- name: python:3.7
  args: ["python","-m","pip","install", "-r", "requirements.txt"]
  id: install requirements

- name: python:3.7
  args: ["python","-m","unittest","discover","--verbose","-s",".","-p","*_test.py"]
  id: unittest