secrets:
- kmsKeyName: projects/gcp-training-144309/locations/global/keyRings/graphQL/cryptoKeys/live
  secretEnv:
    OS_KEY: CiQAOoKuDKDA4YRlHzmUBSGnh7QSH9YY6ibXjwAUcV53f9ofcF8SSQC7QXhlnA3gjaTsmZBhgCF1tMK2DL41woJOwWOqKMbbrShtjodV6bZ+F402FZGw5+D/SKaqDlNgQkK3/s0wWpXnD3IJQOeuYIA=

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Create vars.yaml with secret vars
  entrypoint: /bin/sh
  secretEnv: ['OS_KEY']
  args: ['-c', 'echo "OS_KEY: $$OS_KEY" > vars.yaml']

- name: python:3.7
  args: ["python","-m","unittest","discover","--verbose","-s",".","-p","*_test.py"]
  id: unittest
  