secrets:
- kmsKeyName: projects/graphql-wfs/locations/global/keyRings/graphQL/cryptoKeys/live
  secretEnv:
    OS_KEY: CiQAtMyr9z9pKerbOaHkkXsqSiBm4olI6INVJPcMHS0x7sneqNoSSQBqW3q9GraiXsimyI1f9KH7y8NOYP22+lN7VeUcXJFwn20pJqvAt1ielVVarVjtrEIsh2CM/y0QEn7jSxaPryciEJX4KEiLQm8=

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Create .env with secret vars
  entrypoint: /bin/sh
  secretEnv: ['OS_KEY']
  args: ['-c', 'echo "OS_KEY=$$OS_KEY" > .env']

- name: 'python'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cat .env
      pip install -r requirements.txt
      python -m unittest  --verbose 